from pathlib import Path
import re, json

text = Path('insulin_education_module.md').read_text(encoding='utf-8')
chunks = re.split(r'(?m)^# (?=\d+\. )', text)
modules = []
for chunk in chunks:
    m = re.match(r'(\d+)\.\s+(.+?)\n', chunk)
    if not m:
        continue
    number = int(m.group(1))
    title = m.group(2).strip()
    qas=[]
    qparts = re.split(r'(?m)^### (\d+)\.\s+', chunk)[1:]
    for i in range(0, len(qparts), 2):
        qnum = int(qparts[i])
        block = qparts[i+1]
        lines = block.splitlines()
        q = lines[0].strip()
        a = ''
        for ln in lines[1:]:
            if ln.startswith('**Answer:**'):
                a = ln.replace('**Answer:**','').strip()
                break
        if q and a:
            qas.append({'id': f'{number}-{qnum}', 'question': q, 'answer': a})
    modules.append({'id': number, 'title': title, 'qas': qas})

meta = [
 {"id":1,"kind":"intro","short":"The foundations","tagline":"Build a calm, confident starting point","accent":"#4f46e5","icon":"✦","core":True,"learning":["Explain how insulin and glucose work together","Recognize common glucose symptoms","Know when to ask for help"],"notes":["Diabetes is a group of conditions where glucose remains above the body’s healthy range because insulin is absent, insufficient, or not used effectively.","Your care plan is individualized. A1C, glucose targets, medicines, food, movement and monitoring should be agreed with the diabetes team.","Self-management education is a skill-building process. Bring questions, patterns and barriers to each visit rather than aiming for perfection."],"practice":["Write your care-team contact numbers","Record your personal glucose targets","Make a list of all medicines and devices"],"redFlags":["Severe breathing difficulty or confusion","Persistent vomiting or dehydration","Suspected severe low glucose or DKA"]},
 {"id":2,"kind":"insulin","short":"Insulin skills","tagline":"Use insulin safely and confidently","accent":"#0f766e","icon":"💉","core":True,"learning":["Prepare and inject safely","Rotate sites and protect your skin","Store insulin and manage missed doses"],"notes":["Most routine insulin is delivered into subcutaneous tissue. The current ADA guidance supports short pen needles such as 4 mm for many people, with individualized technique review.","Rotate injections systematically within approved sites. Do not inject into lumps, scars, bruises, wounds or areas of infection.","Never stop basal insulin in type 1 diabetes without urgent professional advice. Missed doses and incorrect insulin can be emergencies.","Pen devices vary: spring-loaded pens (e.g., NovoRapid FlexTouch) need only a light push and their button does not extend, while manual pens (e.g., NovoRapid FlexPen) require active thumb pressure and an extending button—ask for a re-demonstration whenever your device model changes.","Pen hardware details (maximum single dose, dosing increments, battery/replacement guidance) can change when a manufacturer updates or discontinues a model, as already happened with NovoRapid FlexTouch. Treat the specific numbers in this module as a general guide and confirm the current figure on the pack insert or instructions for use for the exact pen in hand."],"practice":["Demonstrate your injection technique to an educator","Mark your next injection area before each dose","Check storage and expiry dates weekly","Confirm your exact pen model and its maximum single dose with your pharmacist"],"redFlags":["Wrong insulin or major dose error","Repeated unexplained highs or lows","Hard, lumpy or infected injection sites","Confusing a concentrated pen (e.g., U-200) with a standard U-100 pen"]},
 {"id":3,"kind":"nutrition","short":"Food & glucose","tagline":"Make meals work for your life","accent":"#c2410c","icon":"🥗","core":False,"learning":["Build a balanced plate","Match carbohydrate, meals and insulin","Adapt nutrition to culture, budget and health"],"notes":["There is no single diabetes diet. A sustainable pattern should fit culture, preferences, food access, medicines, kidney health and personal goals.","A practical plate starts with non-starchy vegetables, a protein source and a high-fiber carbohydrate, with water as the default beverage.","Carbohydrates are not forbidden. Portion, quality, timing and the insulin or medicine plan determine the glucose response."],"practice":["Sketch your usual plate and rebalance it","Measure one familiar carbohydrate portion","Keep a rescue carbohydrate source available"],"redFlags":["Repeated low glucose after missed meals","Unintentional weight loss or inability to eat","Disordered eating or insulin omission for weight control"]},
 {"id":4,"kind":"hypo","short":"Low glucose","tagline":"Spot it. Treat it. Prevent it.","accent":"#dc2626","icon":"⚡","core":True,"learning":["Recognize symptoms and thresholds","Use the 15 g / 15 minute approach","Prepare caregivers for severe lows"],"notes":["A glucose below 70 mg/dL (3.9 mmol/L) is a warning value. A level below 54 mg/dL (3.0 mmol/L) is clinically significant; severe hypoglycemia requires help from another person.","For a conscious person who can swallow, use measured fast-acting glucose and recheck after 15 minutes. Fat-rich foods are slower for initial treatment.","If a person is unconscious, confused or having a seizure, do not give food or drink by mouth. Use glucagon if prescribed and call emergency services."],"practice":["Carry measured fast-acting glucose","Teach one trusted person glucagon use","Write your low-glucose action plan"],"redFlags":["Seizure, unconsciousness or inability to swallow","Repeated lows or nighttime episodes","Low glucose before driving or operating machinery"]},
 {"id":5,"kind":"monitor","short":"Monitor & learn","tagline":"Turn numbers into useful decisions","accent":"#2563eb","icon":"◉","core":True,"learning":["Use SMBG or CGM safely","See patterns, not isolated numbers","Complete preventive health checks"],"notes":["SMBG gives a point-in-time result; CGM adds trends and alerts. Neither replaces a personalized plan or a meter check when symptoms and a device reading disagree.","A1C shows average exposure but not daily variability or lows. Time in range, time below range and pattern review add context.","Diabetes follow-up also includes blood pressure, lipids, kidney, eye, foot, dental, vaccine and emotional-health care as appropriate."],"practice":["Create a simple glucose log","Bring devices and reports to visits","Schedule your next eye, kidney and foot checks"],"redFlags":["Device reading that does not match severe symptoms","Persistent high glucose with ketones","New vision loss, foot wound or chest/stroke symptoms"]},
 {"id":6,"kind":"exercise","short":"Move safely","tagline":"Build activity you enjoy","accent":"#16a34a","icon":"↗","core":False,"learning":["Start gradually and plan for lows","Combine aerobic and strength activity","Protect feet and hydrate"],"notes":["Many adults work toward 150 minutes of moderate-to-vigorous activity weekly across at least 3 days, with resistance exercise 2–3 times weekly when appropriate.","Activity can lower glucose during exercise or later, including overnight. Insulin and sulfonylurea users need a plan for monitoring and rescue carbohydrate.","Avoid vigorous exercise with elevated ketones. Adapt activity for retinopathy, neuropathy, kidney disease, heart disease, pregnancy and foot risk."],"practice":["Choose three realistic movement windows","Carry glucose and water","Check feet before and after activity"],"redFlags":["Chest pain, fainting or severe breathlessness","Ketones, vomiting or confusion","New blister, wound, swelling or color change on a foot"]},
 {"id":7,"kind":"illness","short":"Sick-day plan","tagline":"Prepare before you need it","accent":"#7c3aed","icon":"✚","core":True,"learning":["Monitor glucose and ketones when sick","Prevent dehydration and DKA","Know when to call"],"notes":["Illness hormones can raise glucose even when appetite is low. A written plan should cover monitoring, fluids, food, ketones, insulin, medicines and escalation.","Basal insulin is usually continued in type 1 diabetes. Other medicines may need temporary changes during vomiting, fasting, dehydration, kidney injury or surgery—follow clinician instructions.","Persistent vomiting, moderate/high ketones, deep breathing, confusion or inability to drink require urgent assessment."],"practice":["Pack a sick-day kit","Write your 24-hour contact route","Check ketone strips and glucagon expiry dates"],"redFlags":["Trouble breathing or deep/rapid breathing","Moderate/high or rising ketones","Cannot keep fluids down"]},
 {"id":8,"kind":"dka","short":"DKA awareness","tagline":"Recognize the emergency early","accent":"#be123c","icon":"△","core":True,"learning":["Understand ketones and insulin deficiency","Recognize euglycemic DKA","Use a prevention and backup plan"],"notes":["DKA involves diabetes or hyperglycemia, significant ketones and metabolic acidosis. It is a medical emergency and can occur in type 1, type 2, pregnancy or selected SGLT2 inhibitor users.","Blood beta-hydroxybutyrate is preferred when available. Urine ketones can lag early and remain positive during recovery.","A normal or modest glucose value does not exclude DKA, particularly with SGLT2 inhibitors, pregnancy, fasting or vomiting."],"practice":["Know how to check blood or urine ketones","Keep backup insulin and injection supplies","Write your pump-failure plan if applicable"],"redFlags":["Fruity breath, nausea or abdominal pain","Deep/rapid breathing or drowsiness","Rising ketones or repeated vomiting"]},
 {"id":9,"kind":"complications","short":"Protect organs","tagline":"Prevent what you can; screen early","accent":"#0891b2","icon":"♡","core":False,"learning":["Protect eyes, kidneys, nerves and feet","Reduce heart and stroke risk","Report early warning signs"],"notes":["Complications can be silent early. Glucose, blood pressure, lipids, smoking, kidney health, activity and appropriate medicines all influence risk.","Daily foot inspection and risk-based professional foot checks are essential. Never self-treat a wound with harsh chemicals or untrained cutting.","Retinal, kidney, foot, dental and cardiovascular screening should be scheduled according to diabetes type, duration and risk."],"practice":["Inspect both feet every day","Book screening appointments","Create a smoking-cessation or blood-pressure goal if relevant"],"redFlags":["Sudden vision loss or curtain-like shadow","Foot wound, spreading redness or fever","Chest pain or stroke symptoms"]},
 {"id":10,"kind":"feelings","short":"Emotional health","tagline":"Your feelings are part of care","accent":"#db2777","icon":"☻","core":False,"learning":["Recognize diabetes distress and burnout","Ask for mental-health support","Use nonjudgmental problem-solving"],"notes":["Diabetes distress is the emotional burden of constant self-care; it is common and not a character flaw. Depression and anxiety are treatable clinical conditions.","A good check-in asks both ‘What is your glucose?’ and ‘How are you coping?’ Screening is especially important when care feels impossible or goals change.","If you have thoughts of self-harm, seek immediate help, do not stay alone and tell the care team. Insulin safety planning must be compassionate and individualized."],"practice":["Name one barrier without self-blame","Choose one small action for this week","Tell a trusted person how to help"],"redFlags":["Thoughts of self-harm or not wanting to live","Avoiding insulin or monitoring because of distress","Severe anxiety, depression or disordered eating"]},
 {"id":11,"kind":"travel","short":"Travel smart","tagline":"Carry the plan with you","accent":"#0369a1","icon":"✈","core":False,"learning":["Pack a complete diabetes kit","Plan time zones and device failure","Prevent heat, foot and food problems"],"notes":["Keep insulin, devices and essential medicines in carry-on baggage. Pack extra supplies, a backup meter, ketone tests, rescue carbohydrate, glucagon and a written treatment summary.","Time-zone changes affect meals and basal insulin timing. Obtain a written plan before travel; do not double or skip doses on your own.","Protect insulin from freezing, heat and direct sun. Never walk barefoot, and seek care quickly for foot wounds or illness."],"practice":["Use a two-bag packing system","Add medical identification and contacts","Check airline, device and destination rules"],"redFlags":["Lost insulin or essential treatment","Vomiting, ketones or dehydration abroad","Foot wound or severe low while traveling"]},
 {"id":12,"kind":"pregnancy","short":"Pregnancy care","tagline":"Plan early, monitor closely","accent":"#9333ea","icon":"✿","core":False,"learning":["Use preconception care","Coordinate obstetric and diabetes teams","Prevent lows and ketones"],"notes":["Preconception care reviews glucose, medicines, blood pressure, kidney and eye health, thyroid when indicated, folic acid, vaccines and pregnancy goals.","Pregnancy targets are often lower, which increases hypoglycemia risk. Common ADA/ACOG targets include fasting 70–95 mg/dL and 1-hour after meals 110–140 mg/dL, but the team individualizes them.","Pregnancy can accelerate ketosis and DKA at lower glucose. Vomiting, ketones, abdominal pain or rapid breathing need urgent obstetric-diabetes assessment."],"practice":["Discuss pregnancy intention at visits","Carry glucose and know the glucagon plan","Book postpartum glucose follow-up after GDM"],"redFlags":["Ketones or persistent vomiting","Severe low or inability to eat/drink","Vision change, high blood pressure symptoms or reduced fetal movement"]},
 {"id":13,"kind":"insulintypes","short":"Types & brands","tagline":"Know your insulin by name","accent":"#ca8a04","icon":"🏷","core":True,"learning":["Identify the five action-profile categories of insulin","Match common Indian and US brand names to their molecule and category","Understand why molecule, brand and concentration all matter for safety"],"notes":["Insulins fall into five broad categories by action profile: rapid-acting, short-acting/regular, intermediate-acting (NPH), long/ultra-long-acting basal, and premixed products that blend two profiles.","The same molecule is often sold under different brand names in different countries—for example insulin glargine is Lantus in both India and the US, but also Basaglar in the US and Basalog or Glaritus in India—so the molecule name matters more than the brand.","Brand names can look or sound alike despite very different action profiles—for example Humalog (rapid-acting analog) versus Huminsulin (regular/NPH human insulin)—so always confirm both the molecule and the brand on the label.","Biosimilar and generic versions (such as Basalog, Glaritus, Eglucent or Admelog) are not automatically interchangeable with the original product; switching brands, routes (like inhaled Afrezza) or concentrations (like U100 vs U300) must be directed by the treating physician.","Brand availability, pen hardware specifications and even brand names themselves change over time and by country. Where this module cites a specific device figure (maximum dose, dosing increments) for a regional or lesser-known brand, treat it as a general guide and confirm the current, country-specific prescribing information or pack insert before relying on it."],"practice":["Write down the exact molecule and brand name of every insulin you use","Ask your pharmacist to confirm brand vs molecule at every refill","Note whether each insulin is clear or a cloudy suspension before drawing it up"],"redFlags":["Insulin brand or molecule mismatch from what was prescribed","Switching brands, biosimilars, routes or concentrations without physician guidance","Confusion between similarly named products (e.g., Humalog vs Huminsulin)"]},
  {"id":14,"kind":"storage","short":"Storage of insulin","tagline":"Keep insulin safe and potent","accent":"#0284c7","icon":"❄","core":True,"learning":["Refrigerate unopened insulin at 4 °C","Warm insulin to room temperature before injection","Discard in-use pens or cartridges after 30 days at room temperature"],"notes":["Insulin vials, cartridges, and disposable pens should be refrigerated at 4 °C until required for use. Do not freeze.","Ideally, insulin should be allowed to warm to room temperature before it is injected to prevent stinging and discomfort.","Once a pen or cartridge is in use, it may be kept at room temperature for up to 30 days, following which any residual insulin should be discarded."],"practice":["Check refrigerator temperature and avoid storing near the cooling element","Mark the date opened on your in-use pen or cartridge","Carry insulated cooling pouches when traveling in warm weather"],"redFlags":["Insulin exposed to freezing or direct heat/sunlight","Using in-use pens or cartridges beyond 30 days","Leaving needles attached to stored pens"]},
  {"id":15,"kind":"atlas","short":"Clinical picture atlas","tagline":"Visual guide to regimens, devices & cooling systems","accent":"#0ea5e9","icon":"🖼","core":True,"learning":["Recognize clinical insulin profiles and daily regimens","Identify reusable pens, insulated pouches, and active coolers","Evaluate low-resource evaporative storage systems"],"notes":["Visual familiarity with insulin regimens, delivery pens, travel wallets, and evaporative cooling systems helps prevent medication errors and loss of potency.","Devices range from reusable mechanical pens (e.g., Sanofi AllStar) to specialized travel coolers (FRIO evaporative wallets, CareVego insulated cases, active Peltier fridges, and clay pot Zeer coolers).","Always match your insulin storage method to ambient conditions and transport duration.","Product lineups and stated cooling durations change as manufacturers update or discontinue models; treat the specific hours/temperatures in this module as a general guide and confirm the current specification on the product's own packaging or website before relying on it."],"practice":["Review each visual diagram against your own equipment","Verify cooling durations before traveling","Check digital temperature displays regularly"],"redFlags":["Using evaporative wallets in airtight plastic bags","Freezing insulin in active coolers or ice bags","Confusing premixed regimens with basal-bolus regimens"]},
  {"id":16,"kind":"driving","short":"Driving & lifestyle","tagline":"Stay safe on the road, at work and in daily life","accent":"#b45309","icon":"🚗","core":False,"learning":["Know your disclosure obligations for driving and work","Recognize how alcohol, recreational drugs and shift work affect insulin safety","Use ready-to-use glucagon and medical identification correctly"],"notes":["Legal driving-disclosure rules vary by country; the UK's DVLA requirement is a well-documented example, but always confirm your own jurisdiction's rule and your insurer's requirement.","You are not legally required to disclose diabetes at work unless requesting an accommodation, but disclosure unlocks protections such as breaks, private testing space and shift adjustments in several countries.","Ready-to-use glucagon (nasal or auto-injector) is preferred over older reconstitution kits because caregivers under stress complete a full, correct dose far more reliably with it."],"practice":["Confirm your country's driving-disclosure requirement with your licensing authority","Ask your care team for a written shift-work or travel insulin plan","Get a ready-to-use glucagon prescription and teach a trusted person to use it","Wear or carry medical identification stating you use insulin"],"redFlags":["Driving without checking glucose or after any hypoglycemia symptoms","Continuing to drive after a severe hypoglycemic episode without notifying the licensing authority","No one nearby knows how to use your glucagon"]}
]
meta_by_id={m['id']:m for m in meta}
for mod in modules:
    mod.update(meta_by_id[mod['id']])

out = Path('insulin-education-app/src/data.js')
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('export const modules = ' + json.dumps(modules, ensure_ascii=False, indent=2) + ';\n\nexport const appSources = [\n  { label: "ADA Standards of Care 2026", url: "https://professional.diabetes.org/standards-of-care" },\n  { label: "IDF Type 2 Diabetes Recommendations 2025", url: "https://idf.org/what-we-do/education/idf-clinical-practice-recommendations-for-type-2-diabetes-2025/" },\n  { label: "International DKA Consensus 2024", url: "https://doi.org/10.2337/dci24-0032" },\n  { label: "Endocrine Society / ESE Pregnancy Guidance", url: "https://www.endocrine.org/clinical-practice-guidelines/preexisting-diabetes-in-pregnancy" },\n  { label: "KDIGO Diabetes in CKD", url: "https://kdigo.org/guidelines/diabetes-ckd/" },\n  { label: "IWGDF Foot Guidelines", url: "https://iwgdfguidelines.org/" }\n];\n', encoding='utf-8')
print('wrote', out, 'modules', len(modules), 'qas', sum(len(m['qas']) for m in modules))
